name: Build Debian

on:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - master
    paths:
      - debian/**

jobs:
  build:
    name: "debian:${{ matrix.kind }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        kind:
          - mono
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: ./debian
          file: ./debian/${{ matrix.kind }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/cubxity/pterodactyl-images:debian_${{ matrix.kind }}